/**
 * Bash script that clones (then pulls, then pushes) every repository of an
 * assignment — the "fetch all the students' work for a global review" need.
 *
 * Generated client-side from the detail payload the page already holds: no
 * server route, no CLI, no `gh` dependency. Pure string builder, so the
 * generated shell is unit-tested rather than eyeballed.
 */

export interface CloneScriptInput {
  assignmentName: string;
  /** Assignment slug, used for the file name. */
  slug: string;
  classroomName: string;
  /** `org/repo` full names of the provisioned repositories. */
  repos: readonly string[];
  /** Generation date stamped in the header (injected so tests are stable). */
  generatedAt: Date;
}

/** Downloaded file name of the script. */
export function cloneScriptFileName(slug: string): string {
  return `clone-${slug}.sh`;
}

/** Single-quoted bash literal; repo names are GitHub-safe but quote anyway. */
function quote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/** Free text on a `#` comment line: never let it break out of the comment. */
function comment(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim();
}

export function buildCloneScript(input: CloneScriptInput): string {
  const file = cloneScriptFileName(input.slug);
  const repos = input.repos.map((r) => `  ${quote(r)}`).join("\n");
  return `#!/usr/bin/env bash
# Repositories of "${comment(input.assignmentName)}" — classroom "${comment(input.classroomName)}"
# Generated by HEIG Classroom on ${input.generatedAt.toISOString()}
#
# Usage: ./${file} [--https] [push]
#   (no argument)  clone every repository into ./<name>/, or pull --ff-only
#                  the ones already cloned
#   push           push every repository already cloned here
#   --https        use https:// clone URLs instead of git@github.com:
#
# Individual failures never stop the run; they are listed at the end.
set -euo pipefail

repos=(
${repos}
)

base='git@github.com:'
mode='sync'
while [ $# -gt 0 ]; do
  case "$1" in
    --https) base='https://github.com/' ;;
    push) mode='push' ;;
    *) echo "usage: $0 [--https] [push]" >&2; exit 2 ;;
  esac
  shift
done

done_count=0
skipped=0
failed=()

for repo in "\${repos[@]}"; do
  dir="\${repo##*/}"
  if [ "$mode" = 'push' ]; then
    if [ ! -d "$dir/.git" ]; then
      echo "skip $dir (not cloned)"
      skipped=$((skipped + 1))
      continue
    fi
    if git -C "$dir" push; then
      done_count=$((done_count + 1))
    else
      failed+=("$repo")
    fi
  elif [ -d "$dir/.git" ]; then
    if git -C "$dir" pull --ff-only; then
      done_count=$((done_count + 1))
    else
      failed+=("$repo")
    fi
  else
    if git clone "$base$repo.git" "$dir"; then
      done_count=$((done_count + 1))
    else
      failed+=("$repo")
    fi
  fi
done

echo "$mode: $done_count/\${#repos[@]} repositories done, $skipped skipped, \${#failed[@]} failed"
if [ \${#failed[@]} -gt 0 ]; then
  printf 'failed: %s\\n' "\${failed[@]}" >&2
  exit 1
fi
`;
}
