import { describe, expect, it } from "vitest";

import { buildCloneScript, cloneScriptFileName } from "./cloneScript";

const input = {
  assignmentName: "Labo 02 — quadratic",
  slug: "labo-02-quadratic",
  classroomName: "PRG1 2026",
  repos: ["heig-test/labo-02-quadratic-alice", "heig-test/labo-02-quadratic-bob"],
  generatedAt: new Date("2026-09-16T08:30:00Z"),
};

describe("cloneScriptFileName", () => {
  it("names the script after the assignment slug", () => {
    expect(cloneScriptFileName("labo-02-quadratic")).toBe("clone-labo-02-quadratic.sh");
  });
});

describe("buildCloneScript", () => {
  const script = buildCloneScript(input);

  it("is a strict bash script with a dated header", () => {
    expect(script.startsWith("#!/usr/bin/env bash\n")).toBe(true);
    expect(script).toContain("set -euo pipefail");
    expect(script).toContain('# Repositories of "Labo 02 — quadratic" — classroom "PRG1 2026"');
    expect(script).toContain("Generated by HEIG Classroom on 2026-09-16T08:30:00.000Z");
  });

  it("lists every repository quoted in a bash array", () => {
    expect(script).toContain(
      "repos=(\n  'heig-test/labo-02-quadratic-alice'\n  'heig-test/labo-02-quadratic-bob'\n)",
    );
  });

  it("clones over SSH by default, pulls what is already there, pushes on demand", () => {
    expect(script).toContain("base='git@github.com:'");
    expect(script).toContain("--https) base='https://github.com/'");
    expect(script).toContain('git clone "$base$repo.git" "$dir"');
    expect(script).toContain('git -C "$dir" pull --ff-only');
    expect(script).toContain('git -C "$dir" push');
  });

  it("keeps going on failures and reports them at the end", () => {
    expect(script).toContain('failed+=("$repo")');
    expect(script).toContain("repositories done,");
    expect(script).toContain("printf 'failed: %s\\n'");
  });

  it("escapes single quotes and neutralizes newlines in the header", () => {
    const odd = buildCloneScript({
      ...input,
      assignmentName: "Labo\nrm -rf /",
      classroomName: "O'Brien",
      repos: ["org/it's-a-repo"],
    });
    expect(odd).toContain("# Repositories of \"Labo rm -rf /\" — classroom \"O'Brien\"");
    expect(odd).toContain(`  'org/it'\\''s-a-repo'`);
  });
});
