/**
 * Assignment actions on GitHub: source pickers (org repos, tree), explicit
 * sync, manual lock/unlock and "grade now" on a student repository.
 */
import type { FastifyInstance } from "fastify";
import { eq } from "drizzle-orm";
import { z } from "zod";

import { audit } from "../../audit.js";
import type { AppConfig } from "../../config.js";
import { studentRepos } from "../../db/schema.js";
import { installationClient } from "../../github/app.js";
import { lockStudentRepo, unlockStudentRepo } from "../../github/lock.js";
import { SYNC_QUEUE } from "../../jobs.js";
import { ownedAssignment, ownedClassroomWithOrg, ownedStudentRepo, teacherGuard } from "../guards.js";
import { clientFor } from "./shared.js";

/** Files pre-checked as protected if they exist in the source (GH-30). */
const PROTECTED_CANDIDATES = ["criteria.yml", "README.md", ".github/workflows/grading.yml"];

export async function assignmentActionRoutes(
  app: FastifyInstance,
  opts: { config: AppConfig },
) {
  const { config } = opts;
  const requireTeacher = teacherGuard(app);

  // --- Picker: repositories of the organization ---
  app.get(
    "/app/api/classrooms/:id/org-repos",
    { preHandler: requireTeacher },
    async (req, reply) => {
      const owned = await ownedClassroomWithOrg(app, req, reply);
      if (!owned) return reply;
      const client = await clientFor(config, reply, owned.org);
      if (!client) return reply;
      const { data } = await client.octokit.request("GET /orgs/{org}/repos", {
        org: owned.org.login,
        sort: "pushed",
        direction: "desc",
        per_page: 100,
      });
      // Repositories generated by the platform (squashed, and later the
      // student repositories) are not assignment sources.
      return data
        .filter((r) => !r.archived && !r.name.endsWith("-squashed"))
        .map((r) => ({
          name: r.name,
          defaultBranch: r.default_branch,
          private: r.private,
          pushedAt: r.pushed_at,
        }));
    },
  );

  // --- Exploring a source repository: branches, head, tree ---
  app.get(
    "/app/api/classrooms/:id/org-repos/:repo/tree",
    { preHandler: requireTeacher },
    async (req, reply) => {
      const owned = await ownedClassroomWithOrg(app, req, reply);
      if (!owned) return reply;
      const client = await clientFor(config, reply, owned.org);
      if (!client) return reply;
      const repo = z.string().min(1).max(200).parse((req.params as { repo: string }).repo);
      const owner = owned.org.login;
      let repoData;
      try {
        const res = await client.octokit.request("GET /repos/{owner}/{repo}", {
          owner,
          repo,
          request: { retries: 0 },
        });
        repoData = res.data;
      } catch (err) {
        if ((err as { status?: number }).status === 404) {
          return reply.code(404).send({ error: "repo_not_found", message: "Repository not found" });
        }
        throw err;
      }
      const [{ data: branches }, { data: head }] = await Promise.all([
        client.octokit.request("GET /repos/{owner}/{repo}/branches", {
          owner,
          repo,
          per_page: 100,
        }),
        client.octokit.request("GET /repos/{owner}/{repo}/commits/{ref}", {
          owner,
          repo,
          ref: repoData.default_branch,
        }),
      ]);
      const { data: tree } = await client.octokit.request(
        "GET /repos/{owner}/{repo}/git/trees/{tree_sha}",
        { owner, repo, tree_sha: head.sha, recursive: "1" },
      );
      const MAX_ENTRIES = 800;
      const entries = tree.tree
        .filter((e) => e.path && (e.type === "blob" || e.type === "tree"))
        .slice(0, MAX_ENTRIES)
        .map((e) => ({ path: e.path!, type: e.type as "blob" | "tree" }));
      const files = new Set(entries.filter((e) => e.type === "blob").map((e) => e.path));
      return {
        name: repoData.name,
        repoId: repoData.id,
        defaultBranch: repoData.default_branch,
        branches: branches.map((b) => b.name),
        headSha: head.sha,
        headDate: head.commit.committer?.date ?? head.commit.author?.date ?? null,
        pushedAt: repoData.pushed_at,
        tree: entries,
        truncated: tree.truncated || tree.tree.length > MAX_ENTRIES,
        suggestedProtected: PROTECTED_CANDIDATES.filter((p) => files.has(p)),
      };
    },
  );

  // --- Explicit sync trigger (GH-50/51): the teacher propagates the update ---
  app.post(
    "/app/api/classrooms/:id/assignments/:aid/sync",
    { preHandler: requireTeacher },
    async (req, reply) => {
      const owned = await ownedAssignment(app, req, reply);
      if (!owned) return reply;
      const a = owned.assignment;
      if (a.state === "draft" || a.archivedAt) {
        return reply
          .code(409)
          .send({ error: "not_published", message: "Only published assignments can be synced" });
      }
      if (!a.squashedFullName) {
        return reply
          .code(409)
          .send({ error: "no_squashed", message: "This assignment has no distribution repository" });
      }
      if (!app.boss) {
        return reply
          .code(503)
          .send({ error: "jobs_down", message: "The job queue is not running" });
      }
      await app.boss.send(SYNC_QUEUE, { assignmentId: a.id }, { singletonKey: a.id });
      await audit(app.db, {
        actorUserId: req.user!.id,
        actorType: "user",
        action: "assignment.sync_requested",
        subjectType: "assignment",
        subjectId: a.id,
      });
      return reply.code(202).send({ ok: true });
    },
  );

  // --- Manual lock / unlock of a student repository (US-22: "one more push") ---
  for (const action of ["lock", "unlock"] as const) {
    app.post(
      `/app/api/classrooms/:id/assignments/:aid/repos/:rid/${action}`,
      { preHandler: requireTeacher },
      async (req, reply) => {
        const owned = await ownedStudentRepo(app, req, reply);
        if (!owned) return reply;
        if (owned.org.installationId === null) {
          return reply.code(409).send({ error: "app_not_installed", message: "GitHub App is not installed" });
        }
        const client = await installationClient(config, owned.org.installationId);
        const repoName = owned.repo.fullName!.split("/")[1]!;
        if (action === "lock") {
          await lockStudentRepo(client.octokit, owned.org.login, repoName);
        } else {
          await unlockStudentRepo(client.octokit, owned.org.login, repoName);
        }
        const [updated] = await app.db
          .update(studentRepos)
          .set({ lockedAt: action === "lock" ? new Date() : null })
          .where(eq(studentRepos.id, owned.repo.id))
          .returning();
        await audit(app.db, {
          actorUserId: req.user!.id,
          actorType: "user",
          action: `repo.${action}`,
          subjectType: "student_repo",
          subjectId: owned.repo.id,
          payload: { repo: owned.repo.fullName },
        });
        return updated;
      },
    );
  }

  // --- Manual "grade now" (US-23): run the grading CI on the student's head ---
  // A platform-pushed commit is never graded by design (bot-actor guard in the
  // workflow, bot-commit filter in GR-05), so the manual trigger is a
  // workflow_dispatch: the objective tier runs on the student's own last
  // commit and the grade comes back through the regular ingestion.
  app.post(
    "/app/api/classrooms/:id/assignments/:aid/repos/:rid/grade-now",
    { preHandler: requireTeacher },
    async (req, reply) => {
      const owned = await ownedStudentRepo(app, req, reply);
      if (!owned) return reply;
      if (owned.org.installationId === null) {
        return reply.code(409).send({ error: "app_not_installed", message: "GitHub App is not installed" });
      }
      const client = await installationClient(config, owned.org.installationId);
      const repoName = owned.repo.fullName!.split("/")[1]!;
      const ref = owned.repo.defaultBranch ?? owned.assignment.branches[0] ?? "main";
      try {
        await client.octokit.request(
          "POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches",
          { owner: owned.org.login, repo: repoName, workflow_id: "grading.yml", ref },
        );
      } catch (err) {
        const status = (err as { status?: number }).status;
        // 404: no grading.yml; 422: the workflow has no workflow_dispatch trigger.
        if (status === 404 || status === 422) {
          return reply.code(409).send({
            error: "no_manual_grading",
            message: "The grading workflow of this repository does not support manual runs",
          });
        }
        throw err;
      }
      await audit(app.db, {
        actorUserId: req.user!.id,
        actorType: "user",
        action: "repo.grade_now",
        subjectType: "student_repo",
        subjectId: owned.repo.id,
        payload: { repo: owned.repo.fullName, ref },
      });
      return reply.code(202).send({ ok: true });
    },
  );
}
